name: Dotty

on:
  push:
  pull_request:

env:
  DOTTY_CI_RUN: true


jobs:
  test:
    runs-on: [self-hosted, Linux, playground]
    container:
      image: lampepfl/dotty:2021-03-22
      options: --cpu-shares 4096
      volumes:
        - ${{ github.workspace }}/../../cache/sbt:/root/.sbt
        - ${{ github.workspace }}/../../cache/ivy:/root/.ivy2/cache
        - ${{ github.workspace }}/../../cache/general:/root/.cache
    if: github.event_name == 'push'

    steps:
      - name: Set JDK 16 as default
        run: echo "/usr/lib/jvm/java-16-openjdk-amd64/bin" >> $GITHUB_PATH

      - name: Checkout cleanup script
        uses: actions/checkout@v2

      - name: Test
        run: cat .gitmodules | grep psbp
